---
- name: CHECK CONNECTIVITY
  hosts: routers, switches
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: Test connectivity to router
    cisco.ios.ios_ping:
      dest: 192.168.1.1
    register: result
  - debug:
      var=result
  - name: Test connectivity to switch
    cisco.ios.ios_ping:
      dest: 192.168.1.2
    register: result
  - debug:
      var=result
