---
- name: CHECK CONNECTIVITY
  hosts: routers, switches
  gather_facts: false
  connection: local

  tasks:
  - name: Test connectivity to management IP
    ping:
      data: 
        - "192.168.1.1"
        - "192.168.1.2"
    register: result
  - debug:
      var=result
