---
- name: BASIC CONFIG
  hosts: routers, switches
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Set hostname, domain name, enable SSH
      cisco.ios.ios_config:
        lines: 
          - "hostname {{ inventory_hostname }}"
          - "ip domain-name devnet4.com"
          - "ip ssh version 2"

    - name: Terminal lines
      cisco.ios.ios_config:
        lines:
          - transport input ssh
          - login local
        parents: line vty 0 15

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
