---
- name: Configure VLANs
  hosts: switches
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: Config VLANs
    cisco.ios.ios_vlans:
      config:
        - name: Vlan10
          vlan_id: 10
        - name: Vlan20
          vlan_id: 20
      state: merged

  - name: Assign IP address to VLAN 10
    cisco.ios.ios_l3_interfaces:
      config:
        - name: Vlan10
          ipv4: 
            - address: 192.168.10.1/24
        - name: Vlan20
          ipv4:
            - address: 192.168.20.1/24
      state: merged
